spring.application.name=proyecto-uni


# configuración de la base de datos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/proyectounidb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# OpenAI configuration
openai.api.key=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
